version: '3'
networks:
    proxy:
        external:
            name: proxy
services:
    nginx:
        image: nginx:1.17
        volumes:
        - ./nginx.conf:/etc/nginx/nginx.conf
        environment:
        - NGINX_HOST=purplebirdman.online
        - NGINX_PORT=80
        ports:
        - 80:80
        - 443:443
        networks:
        - proxy
