version: '3'
networks:
    proxy:
        external: true
services:
    web:
        image: nginx:1.27-alpine
        volumes:
        - /etc/letsencrypt/:/etc/letsencrypt/
        - ./conf.d/:/etc/nginx/conf.d/
        environment:
        - NGINX_HOST=purplebirdman.com
        - NGINX_PORT=443
        ports:
        - 443:443
        networks:
        - proxy
