# requires variable config loading, such as:
# docker stack deploy -c <(docker-compose config) proxy
#
# also needs an .env file with some variables!

version: '3'
networks:
    proxy:
        external: true
services:
    web:
        image: nginx:1.17
        volumes:
        - /etc/letsencrypt/:/etc/letsencrypt/
        - ./nginx.conf:/etc/nginx/nginx.conf
        - ./conf.d/:/etc/nginx/conf.d/
        environment:
        - NGINX_HOST=purplebirdman.com
        - NGINX_PORT=443
        ports:
        - 443:443
        networks:
        - proxy
