version: '3'
networks:
    proxy:
        external:
            name: proxy
services:
    nginx:
        image: nginx:1.17
        restart: on-failure
        deploy:
            restart_policy:
                condition: on-failure
                delay: 5s
                max_attempts: 5
                window: 10s
        volumes:
        - ./nginx.conf:/etc/nginx/nginx.conf
        environment:
        - NGINX_HOST=purplebirdman.com
        - NGINX_PORT=80
        ports:
        - 80:80
        - 443:443
        networks:
        - proxy
