version: '3'
networks:
    proxy:
        external:
            name: proxy
services:
    proxy:
        image: nginx:1.17
        volumes:
        - ./nginx.conf:/etc/nginx/nginx.conf
        environment:
        - NGINX_HOST=purplebirdman.online
        - NGINX_PORT=80
        ports:
        - 8080:80
        networks:
        - default
        - proxy
